AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Planify Notification Service - Reminder Scheduler Lambda

Globals:
    Function:
        Timeout: 60
        MemorySize: 512
        Runtime: java21

Parameters:
    DatabaseUrl:
        Type: String
        Description: PostgreSQL database connection URL
    DatabaseUsername:
        Type: String
        Description: Database username
    DatabasePassword:
        Type: String
        NoEcho: true
        Description: Database password
    SendGridApiKey:
        Type: String
        NoEcho: true
        Description: SendGrid API key
    TwilioAccountSid:
        Type: String
        Description: Twilio Account SID
    TwilioAuthToken:
        Type: String
        NoEcho: true
        Description: Twilio Auth Token
    TwilioPhoneNumber:
        Type: String
        Description: Twilio phone number

Resources:
    ReminderSchedulerFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/notification-service-1.0.0-SNAPSHOT-lambda.jar
            Handler: com.planify.notification.lambda.ReminderSchedulerHandler::handleRequest
            Environment:
                Variables:
                    SPRING_DATASOURCE_URL: !Ref DatabaseUrl
                    SPRING_DATASOURCE_USERNAME: !Ref DatabaseUsername
                    SPRING_DATASOURCE_PASSWORD: !Ref DatabasePassword
                    SENDGRID_API_KEY: !Ref SendGridApiKey
                    TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
                    TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
                    TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
                    SPRING_KAFKA_BOOTSTRAP_SERVERS: ""
            Events:
                ScheduleEvent:
                    Type: Schedule
                    Properties:
                        Schedule: rate(30 minutes)
                        Description: Check and send scheduled event reminders every 30 minutes
                        Enabled: true
            Policies:
                - VPCAccessPolicy: {}

Outputs:
    ReminderSchedulerFunction:
        Description: "Reminder Scheduler Lambda Function ARN"
        Value: !GetAtt ReminderSchedulerFunction.Arn
    ReminderSchedulerFunctionIamRole:
        Description: "IAM Role for Lambda Function"
        Value: !GetAtt ReminderSchedulerFunctionRole.Arn
