-- Insert Default Templates
INSERT INTO notification_templates (template_key, type, subject, body_template, sms_template, language) VALUES
('NEW_INVITATION', 'EMAIL_APP', 'You''re invited new organization',
'<h2>You''re Invited to join organization!</h2><p>Hello $${recipientName},</p><p>You have been invited to join <strong>$${orgName}</strong> organization.<p>If you want to join this organization or view all your invitations, please click the link below:</p><a href="$${invitatioAcceptLink}">Join the organization</a>',
null,
'en'),
('INVITATION_ACCEPTED', 'APP', 'New user in your organization',
'<h2>New User Joined Your Organization</h2><p>Hello $${adminName},</p><p>User <strong>$${userName}</strong> has accepted the invitation to join your organization <strong>$${orgName}</strong>.</p><p>You can view the updated member list by clicking the link below:</p><a href="$${memberListLink}">View Members</a>',
null,
'en'),
('INVITATION_DECLINED', 'APP', 'Invitation Declined',
'<h2>Invitation Declined</h2><p>Hello $${adminName},</p><p>User <strong>$${userName}</strong> has declined the invitation to join your organization <strong>$${orgName}</strong>.</p>',
null,
'en'),
('NEW_REQUEST', 'APP', 'New request to join organization',
'<h2>New Request to Join Your Organization</h2><p>Hello $${adminName},</p><p>User <strong>$${userName}</strong> has requested to join your organization <strong>$${orgName}</strong>.</p><p>Please review the request by clicking the link below :</p><a href="$${requestReviewLink}">Review Request</a>',
null,
'en'),
('REQUEST_ACCEPTED', 'EMAIL_APP', 'You''re now a member of organization',
'<h2>Welcome to the Organization!</h2><p>Hello $${userName},</p><p>Your request to join the organization <strong>$${orgName}</strong> has been accepted.</p>',
null,
'en'),
('REQUEST_DECLINED', 'EMAIL_APP', 'Your request to join organization was declined',
'<h2>Request Declined</h2><p>Hello $${userName},</p><p>We regret to inform you that your request to join the organization <strong>$${orgName}</strong> has been declined.</p>',
null,
'en')